{% set python_min = '3.10' %}
{% set name = "flowermd" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmelab/flowerMD/archive/{{ version }}.tar.gz
  sha256: 2fd65da391f727f76ff8dc152929571580395936267b77c5b606d321fc8682fd

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1 
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - foyer >=0.12.0
    - freud >=3.0
    - grits >=0.5.0
    - cmeutils >=1.3
    - gsd >=3.0
    - gmso >=0.12.0
    - hoomd >=4.6, !=5.3.0
    - mbuild >0.17.0
    - numpy <2.0
    - openbabel >=3
    - py3Dmol
    - fresnel >=0.13.5

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-xdist
  source_files:
    - flowermd/tests/
  imports:
    - flowermd
  commands:
    - |
      echo "Running filtered tests..."
      pytest -v -n auto \
        --deselect flowermd/tests/base/test_forcefield.py::TestBaseForcefield::test_base_xml_forcefield \
        --deselect flowermd/tests/base/test_molecule.py::TestMolecule::test_molecule_from_file \
        --deselect flowermd/tests/base/test_molecule.py::TestMolecule::test_validate_force_field_xml_file_path \
        --deselect flowermd/tests/base/test_molecule.py::TestMolecule::test_validate_force_field_hoomd_ff_missing_Coulomb \
        --deselect flowermd/tests/base/test_system.py::TestSystem::test_system_from_mol2_mol_parameterization \
        --deselect flowermd/tests/library/test_forcefields.py::TestForceFields::test_FF_from_file \
        --deselect flowermd/tests/library/test_forcefields.py::TestTableForcefield::test_from_txt_file \
        --deselect flowermd/tests/library/test_forcefields.py::TestTableForcefield::test_from_csv_file \
        --deselect flowermd/tests/library/test_forcefields.py::TestTableForcefield::test_from_npy_file \
        --deselect flowermd/tests/modules/test_surface_wetting.py::TestInterfaceBuilder::test_interface_builder \
        --deselect flowermd/tests/modules/test_surface_wetting.py::TestWettingSimulation::test_wetting_sim \
        --deselect flowermd/tests/utils/test_ff_utils.py::TestFFUtils::test_find_xml_ff_path \
        --deselect flowermd/tests/utils/test_ff_utils.py::TestFFUtils::test_xml_to_gmso_ff \
        flowermd/tests/

about:
  home: https://github.com/cmelab/flowerMD
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Flexible library of organic workflows and extensible recipes for molecular dynamics."
  description: |
    flowerMD is a modular wrapper package for molecular dynamics (MD)
    simulation pipeline development, designed to enable fast, reproducible,
    end-to-end simulation workflows with minimal user effort.
  dev_url: https://github.com/cmelab/flowerMD
  doc_url: https://flowermd.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - chrisjonesBSU
    - marjanalbooyeh
    - erjank
